#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

# ============================================================================ #
#                          C h e c k o v   c o n f i g
# ============================================================================ #

# https://github.com/bridgecrewio/checkov#configuration-using-a-config-file
#
# This is not well documented but the fields seem to be the same as:
#
#   checkov --help

---
#branch: master
#check:
#  - CKV_DOCKER_1
compact: true
directory:
  - .
skip-path:
  - jenkins
  - github-actions
  - kubernetes-templates
  - terraform-templates
#docker-image: nholuongut/bash-tools
#dockerfile-path: Dockerfile
download-external-modules: true  # without this gets lots of annoying warning lines such as '2022-02-22 16:14:40,180 [MainThread  ] [WARNI]  Failed to download module x/y/z:n.n.n'
#evaluate-variables: true
#external-checks-dir:
#  - sample-dir
#external-modules-download-path: .external_modules
framework:
  - all
no-guide: true
output: cli
quiet: true
#repo-id: nholuongut/DevOps-Bash-tools  # what to report to Bridgecrew Cloud - without this gets annoying duplicate repos such as 'nholuongut_cli_repo/bash-tools'
#skip-check:
#  - CKV_DOCKER_3
#  - CKV_DOCKER_2
#skip-fixes: true
#skip-framework:
#  - dockerfile
#  - secrets
skip-suppressions: true
soft-fail: true
