#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
# ============================================================================ #
#                               C i r r u s   C I
# ============================================================================ #

# https://cirrus-ci.org/guide/writing-tasks/

container:
  image: ubuntu:18.04

task:
  env:
    TMPDIR: /var/tmp
  script:
    - setup/ci_bootstrap.sh
    - make init
    - make ci test
