#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
# ============================================================================ #
#                            C o n c o u r s e   C I
# ============================================================================ #

# https://concourse-ci.org/golang-library-example.html

# https://resource-types.concourse-ci.org/
# https://concourse-ci.org/resource-types.html
resources:
  - name: github
    icon: github-circle
    type: git
    source:
      uri: https://github.com/nholuongut/devops-bash-tools  # XXX: Edit
      branch: master
  #- name: daily
  #  type: time
  #  source:
  #    interval: 1d

# https://concourse-ci.org/jobs.html
jobs:
  - name: build
    public: false
    plan:
      - get: github  # from resource above
        trigger: true
        #version: every  # build every git commit, default: latest
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest
          inputs:
            - name: github
              path: code
          params:
            CONCOURSE: 1
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd code &&
                setup/ci_bootstrap.sh &&
                make init &&
                make ci test
