---
# XXX: putting this separator further down with code causes a parsing bug in drone lint
#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
# ============================================================================ #
#                                D r o n e   C I
# ============================================================================ #

# https://docs.drone.io/quickstart/cli/
#
# https://docs.drone.io/cli/install/
#
# brew install drone-cli
#
# cd to this directory
#
# drone exec [--pipeline default] [--include=thisstep] [--exclude=thatstep]

kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ubuntu:18.04
    #environment:
    #  DEBUG: 1
    commands:
      - setup/ci_bootstrap.sh
      - make init
      - make ci
      - make test

trigger:
  branch:
    - master
