#  vim:ts=4:sts=4:sw=4:et
#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#


ignored:
  # Maintainer is deprecated
  #- DL4000
  # FROM latest - dev images build on upstream latest tag intentionally
  - DL3007
  # apt-get install versions need not be pinned
  - DL3008
  # apk add versions need not be pinned
  - DL3018
  #- SC1010
  # - for dev images it's ok to use both curl and wget as they are dependencies of different scripts
  - DL4001

trustedRegistries:
  - docker.io
  #- my-company.com:5000
