#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

# ============================================================================ #
#                         P r e - C o m m i t   H o o k
# ============================================================================ #

---
#- id: trailing-whitespace
#  name: Trim Trailing Whitespace
#  description: This hook trims trailing whitespace.
#  entry: trailing-whitespace-fixer
#  language: python
#  types: [text]
