#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

# ============================================================================ #
#                              P r o m e t h e u s
# ============================================================================ #

---
global:
  scrape_interval: 15s # default: 1 minute
  evaluation_interval: 15s # evaluate rules every 15 sess (default: 1 minute)
  #scrape_timeout: 10s

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # job_name adds label `job=<job_name>` to timeseries metrics
  - job_name: prometheus
    #metrics_path: /metrics
    #scheme: http
    #honor_timestamps: true
    #enable_compression: true
    #follow_redirects: true
    #enable_http2: true
    static_configs:
      - targets:
          - localhost:9090

  - job_name: demo
    static_configs:
      - targets:
          - demo.promlabs.com:10000
          - demo.promlabs.com:10001
          - demo.promlabs.com:10002

  - job_name: node
    static_configs:
      - targets:
        - localhost:9100  # run ./node_exporter on the host - see https://github.com/nholuongut/Knowledge-Base/blob/main/prometheus.md
