#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

# ============================================================================ #
#                               F o r k   S y n c
# ============================================================================ #

# For a fork of the original repo, activate to keep it up to date via straight GitHub sync to the default branch

---
name: Fork Sync

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fork_sync:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == true
    if: github.repository_owner != 'nholuongut'
    name: Fork Sync
    uses: nholuongut/GitHub-Actions/.github/workflows/fork-sync.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
