#  vim:ts=2:sts=2:sw=2:et
#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

# ============================================================================ #
#                        R e d h a t   K i c k s t a r t
# ============================================================================ #

---
name: Redhat Kickstart

on:
  push:
    branches:
      - master
      - main
    paths:
      - anaconda-ks.cfg
      - .github/workflows/kickstart.yaml  # this workflow

  pull_request:
    branches:
      - master
      - main
    paths:
      - anaconda-ks.cfg
      - .github/workflows/kickstart.yaml  # this workflow

  workflow_dispatch:

permissions:
  contents: read

jobs:
  kickstart:
    name: Kickstart
    uses: nholuongut/GitHub-Actions/.github/workflows/kickstart.yaml@master
    with:
      files: anaconda-ks.cfg ks.cfg kickstart.cfg
