#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
# ============================================================================ #
#                                M a r k D o w n
# ============================================================================ #

---
name: Markdown

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .mdlrc
      - .mdl.rb
      - .markdownlint.rb
      - .github/workflows/markdown.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .mdlrc
      - .mdl.rb
      - .markdownlint.rb
      - .github/workflows/markdown.yaml
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  Markdown:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'nholuongut'
    name: Markdown
    uses: nholuongut/GitHub-Actions/.github/workflows/markdown.yaml@master
