#  vim:ts=2:sts=2:sw=2:et
#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
# ============================================================================ #
#                        H a s h i C o r p   P a c k e r
# ============================================================================ #

---
name: HashiCorp Packer

on:
  push:
    branches:
      - master
      - main
    paths:
      - template.pkr.hcl
      - .github/workflows/packer.yaml  # this workflow

  pull_request:
    branches:
      - master
      - main
    paths:
      - template.pkr.hcl
      - .github/workflows/packer.yaml  # this workflow

  workflow_dispatch:

permissions:
  contents: read

jobs:
  packer:
    name: Packer
    uses: nholuongut/GitHub-Actions/.github/workflows/packer.yaml@master
