#  vim:ts=2:sts=2:sw=2:et
#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
# ============================================================================ #
#                          D e b i a n   P r e s e e d
# ============================================================================ #

---
name: Debian Preseed

on:
  push:
    branches:
      - master
      - main
    paths:
      - preseed.cfg
      - .github/workflows/preseed.yaml  # this workflow

  pull_request:
    branches:
      - master
      - main
    paths:
      - preseed.cfg
      - .github/workflows/preseed.yaml  # this workflow

  workflow_dispatch:

permissions:
  contents: read

jobs:
  preseed:
    name: Preseed
    uses: nholuongut/GitHub-Actions/.github/workflows/preseed.yaml@master
